# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8822479920882f1a17b8ba6845de5ca6201a3341db8b40897ec4bfe938ed9bf4a22979ee784d6827eeb4382b0380812fdb659197e4909d856dcd6949f81e729b

test:
  secret_key_base: df10fb5af50ba9bede49c38836cc0770e56142eb12955853ff5cf9c0a2d772103f64a08b25f31dd060e5302ec0b63f015403ae063ccc55767c3e786260eafa5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
